manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ebastler
      url-base: https://github.com/ebastler
    - name: max17048
      url-base: https://github.com/zhiayang
  projects:
    - name: zmk
      remote: max17048
      revision: sensor-driver-max17048
      import: app/west.yml
  self:
    path: config
