manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Croktopus
      url-base: https://github.com/Croktopus
  projects:
    - name: zmk
      remote: Croktopus
      revision: main
      import: app/west.yml
  self:
    path: config
